language: php

php:
  - 5.3
  - 5.6
  - 7.0
  - 7.1
  - hhvm

script:
  - git clone https://github.com/SimpleMachines/BuildTools.git other/buildTools > /dev/null 2>&1
  - cd other/buildTools/ && git fetch && git pull && cd ../../ 
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
  - if php other/buildtools/check-signed-off.php | grep "Error:"; then php other/buildtools/check-signed-off.php; exit 1; fi
  - if find . -name "*.php" -exec php other/buildtools/check-smf-license.php {} 2>&1 \; | grep "Error:"; then exit 1; fi
  - if find . -name "./Themes/default/languages/*.english.php" -exec php other/buildtools/check-smf-langauge.php {} 2>&1 \; | grep "Error:"; then exit 1; fi
  - if find . -name "*.php" -exec php other/buildtools/check-eof.php {} 2>&1 \; | grep "Error:"; then exit 1; fi
